DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS(
  ID INT GENERATED ALWAYS As IDENTITY PRIMARY KEY NOT NULL,
  NOME TEXT NOT NULL,
  PODER TEXT NOT NULL
);

---Create
INSERT INTO TB_HEROIS (NOME, PODER)
VALUES
('Flash', 'Velocidade'),
('Aquaman', 'Falar com os animais')
('Batman', 'Dinheir');

--Read

SELECT * from TB_HEROIS;
SELECT * from TB_HEROIS WHERE NOME = 'Flash';


--update

UPDATE TB_HEROIS
SET NOME= 'Goku', PODER= 'Deus'
WHERE ID = 1;

-- delete

DELETE FROM TB_HEROIS WHERE ID =2;